// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module main_padv4_Pipeline_VITIS_LOOP_203_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sizeNeeded_out,
        sizeNeeded_out_ap_vld,
        p_cond_out,
        p_cond_out_ap_vld,
        sub_ln203_out,
        sub_ln203_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] sizeNeeded_out;
output   sizeNeeded_out_ap_vld;
output  [0:0] p_cond_out;
output   p_cond_out_ap_vld;
output  [31:0] sub_ln203_out;
output   sub_ln203_out_ap_vld;

reg ap_idle;
reg sizeNeeded_out_ap_vld;
reg p_cond_out_ap_vld;
reg sub_ln203_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln203_fu_126_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sizeNeeded_2_reg_149;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] sizeNeeded_fu_38;
wire   [31:0] sizeNeeded_3_fu_132_p2;
reg   [31:0] ap_sig_allocacmp_sizeNeeded_2;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_fu_72_p3;
wire   [31:0] sub_ln203_fu_85_p2;
wire   [8:0] trunc_ln203_1_fu_92_p1;
wire   [9:0] p_and_t_cast_fu_96_p3;
wire   [8:0] trunc_ln203_fu_81_p1;
wire   [9:0] sub_ln203_1_fu_104_p2;
wire   [9:0] tmp_s_fu_110_p3;
wire   [9:0] select_ln203_fu_118_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

main_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            sizeNeeded_fu_38 <= 32'd25;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            sizeNeeded_fu_38 <= sizeNeeded_3_fu_132_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sizeNeeded_2_reg_149 <= ap_sig_allocacmp_sizeNeeded_2;
    end
end

always @ (*) begin
    if (((icmp_ln203_fu_126_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ap_sig_allocacmp_sizeNeeded_2 = 32'd25;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ap_sig_allocacmp_sizeNeeded_2 = sizeNeeded_3_fu_132_p2;
        end else begin
            ap_sig_allocacmp_sizeNeeded_2 = sizeNeeded_fu_38;
        end
    end else begin
        ap_sig_allocacmp_sizeNeeded_2 = sizeNeeded_fu_38;
    end
end

always @ (*) begin
    if (((icmp_ln203_fu_126_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_cond_out_ap_vld = 1'b1;
    end else begin
        p_cond_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln203_fu_126_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sizeNeeded_out_ap_vld = 1'b1;
    end else begin
        sizeNeeded_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln203_fu_126_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sub_ln203_out_ap_vld = 1'b1;
    end else begin
        sub_ln203_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln203_fu_126_p2 = ((select_ln203_fu_118_p3 == 10'd448) ? 1'b1 : 1'b0);

assign p_and_t_cast_fu_96_p3 = {{1'd0}, {trunc_ln203_1_fu_92_p1}};

assign p_cond_out = ap_sig_allocacmp_sizeNeeded_2[32'd31];

assign select_ln203_fu_118_p3 = ((tmp_fu_72_p3[0:0] == 1'b1) ? sub_ln203_1_fu_104_p2 : tmp_s_fu_110_p3);

assign sizeNeeded_3_fu_132_p2 = (sizeNeeded_2_reg_149 + 32'd1);

assign sizeNeeded_out = sizeNeeded_fu_38;

assign sub_ln203_1_fu_104_p2 = (10'd0 - p_and_t_cast_fu_96_p3);

assign sub_ln203_fu_85_p2 = (32'd0 - ap_sig_allocacmp_sizeNeeded_2);

assign sub_ln203_out = sub_ln203_fu_85_p2;

assign tmp_fu_72_p3 = ap_sig_allocacmp_sizeNeeded_2[32'd31];

assign tmp_s_fu_110_p3 = {{1'd0}, {trunc_ln203_fu_81_p1}};

assign trunc_ln203_1_fu_92_p1 = sub_ln203_fu_85_p2[8:0];

assign trunc_ln203_fu_81_p1 = ap_sig_allocacmp_sizeNeeded_2[8:0];

endmodule //main_padv4_Pipeline_VITIS_LOOP_203_1
