-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity main_padv4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    messageBlocks_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
    messageBlocks_ce0 : OUT STD_LOGIC;
    messageBlocks_we0 : OUT STD_LOGIC;
    messageBlocks_d0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (24 downto 0) );
end;


architecture behav of main_padv4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv5_11 : STD_LOGIC_VECTOR (4 downto 0) := "10001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv25_1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv17_200 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal message5binary_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal message5binary_ce0 : STD_LOGIC;
    signal message5binary_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln207_fu_207_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln207_reg_423 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal blocksNeeded_fu_219_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal blocksNeeded_reg_429 : STD_LOGIC_VECTOR (24 downto 0);
    signal icmp_ln209_fu_225_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln209_reg_433 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln209_fu_231_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln209_reg_437 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln213_fu_284_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln213_reg_442 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln213_1_fu_320_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal select_ln213_1_reg_448 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln224_fu_342_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln224_reg_453 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln213_1_fu_368_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln213_1_reg_459 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_done : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_idle : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_ready : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out_ap_vld : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_sizeNeeded_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_sizeNeeded_3_out_ap_vld : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_ce0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_done : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_idle : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_ready : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sizeNeeded_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sizeNeeded_out_ap_vld : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_p_cond_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_p_cond_out_ap_vld : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sub_ln203_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sub_ln203_out_ap_vld : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_done : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_idle : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_ready : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_ce0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_we0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_d0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_ce0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_done : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_idle : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_ready : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_ce0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_we0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_d0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_done : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_idle : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_ready : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_address0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_ce0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_we0 : STD_LOGIC;
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_d0 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_phi_mux_iter_0_lcssa_phi_fu_107_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal iter_0_lcssa_reg_103 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state6_on_subcall_done : BOOLEAN;
    signal grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal sizeNeeded_3_loc_fu_72 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_cond_loc_fu_64 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln203_loc_fu_60 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start_reg : STD_LOGIC := '0';
    signal grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal zext_ln213_2_fu_373_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal zext_ln226_fu_382_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal trunc_ln207_1_fu_173_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln207_fu_183_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal trunc_ln207_2_fu_193_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub_ln207_fu_187_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln207_1_fu_203_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln207_fu_215_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal trunc_ln213_1_fu_240_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_ln213_fu_252_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln213_2_fu_258_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_fu_244_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub_ln213_1_fu_268_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_3_fu_274_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln213_fu_236_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln213_2_fu_300_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_and_t3_cast_fu_306_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln213_3_fu_314_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_and_f_cast_fu_292_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln224_1_fu_331_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_cast_fu_334_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln224_fu_328_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_351_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln213_1_fu_358_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln213_fu_348_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln213_fu_362_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln226_fu_377_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component main_padv4_Pipeline_VITIS_LOOP_10_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        strLength_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        strLength_out_ap_vld : OUT STD_LOGIC;
        sizeNeeded_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sizeNeeded_3_out_ap_vld : OUT STD_LOGIC;
        message5binary_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        message5binary_ce0 : OUT STD_LOGIC;
        message5binary_q0 : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component main_padv4_Pipeline_VITIS_LOOP_203_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sizeNeeded_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        sizeNeeded_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sizeNeeded_out_ap_vld : OUT STD_LOGIC;
        p_cond_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        p_cond_out_ap_vld : OUT STD_LOGIC;
        sub_ln203_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        sub_ln203_out_ap_vld : OUT STD_LOGIC );
    end component;


    component main_padv4_Pipeline_VITIS_LOOP_209_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        trunc_ln1 : IN STD_LOGIC_VECTOR (30 downto 0);
        messageBlocks_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        messageBlocks_ce0 : OUT STD_LOGIC;
        messageBlocks_we0 : OUT STD_LOGIC;
        messageBlocks_d0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        message5binary_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        message5binary_ce0 : OUT STD_LOGIC;
        message5binary_q0 : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component main_padv4_Pipeline_VITIS_LOOP_215_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        iter_0_lcssa : IN STD_LOGIC_VECTOR (31 downto 0);
        messageBlocks_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        messageBlocks_ce0 : OUT STD_LOGIC;
        messageBlocks_we0 : OUT STD_LOGIC;
        messageBlocks_d0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component main_padv4_Pipeline_VITIS_LOOP_223_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        add_ln224 : IN STD_LOGIC_VECTOR (16 downto 0);
        messageBlocks_address0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        messageBlocks_ce0 : OUT STD_LOGIC;
        messageBlocks_we0 : OUT STD_LOGIC;
        messageBlocks_d0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component main_padv4_message5binary_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    message5binary_U : component main_padv4_message5binary_ROM_AUTO_1R
    generic map (
        DataWidth => 5,
        AddressRange => 2617,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => message5binary_address0,
        ce0 => message5binary_ce0,
        q0 => message5binary_q0);

    grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115 : component main_padv4_Pipeline_VITIS_LOOP_10_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start,
        ap_done => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_done,
        ap_idle => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_idle,
        ap_ready => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_ready,
        strLength_out => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out,
        strLength_out_ap_vld => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out_ap_vld,
        sizeNeeded_3_out => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_sizeNeeded_3_out,
        sizeNeeded_3_out_ap_vld => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_sizeNeeded_3_out_ap_vld,
        message5binary_address0 => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_address0,
        message5binary_ce0 => grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_ce0,
        message5binary_q0 => message5binary_q0);

    grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123 : component main_padv4_Pipeline_VITIS_LOOP_203_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start,
        ap_done => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_done,
        ap_idle => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_idle,
        ap_ready => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_ready,
        sizeNeeded_3_reload => sizeNeeded_3_loc_fu_72,
        sizeNeeded_out => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sizeNeeded_out,
        sizeNeeded_out_ap_vld => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sizeNeeded_out_ap_vld,
        p_cond_out => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_p_cond_out,
        p_cond_out_ap_vld => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_p_cond_out_ap_vld,
        sub_ln203_out => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sub_ln203_out,
        sub_ln203_out_ap_vld => grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sub_ln203_out_ap_vld);

    grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131 : component main_padv4_Pipeline_VITIS_LOOP_209_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start,
        ap_done => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_done,
        ap_idle => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_idle,
        ap_ready => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_ready,
        trunc_ln1 => trunc_ln209_reg_437,
        messageBlocks_address0 => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_address0,
        messageBlocks_ce0 => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_ce0,
        messageBlocks_we0 => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_we0,
        messageBlocks_d0 => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_d0,
        message5binary_address0 => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_address0,
        message5binary_ce0 => grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_ce0,
        message5binary_q0 => message5binary_q0);

    grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140 : component main_padv4_Pipeline_VITIS_LOOP_215_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start,
        ap_done => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_done,
        ap_idle => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_idle,
        ap_ready => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_ready,
        iter_0_lcssa => iter_0_lcssa_reg_103,
        messageBlocks_address0 => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_address0,
        messageBlocks_ce0 => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_ce0,
        messageBlocks_we0 => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_we0,
        messageBlocks_d0 => grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_d0);

    grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148 : component main_padv4_Pipeline_VITIS_LOOP_223_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start,
        ap_done => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_done,
        ap_idle => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_idle,
        ap_ready => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_ready,
        add_ln224 => add_ln224_reg_453,
        messageBlocks_address0 => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_address0,
        messageBlocks_ce0 => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_ce0,
        messageBlocks_we0 => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_we0,
        messageBlocks_d0 => grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_ready = ap_const_logic_1)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_ready = ap_const_logic_1)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln209_fu_225_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_ready = ap_const_logic_1)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_ready = ap_const_logic_1)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_ready = ap_const_logic_1)) then 
                    grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    iter_0_lcssa_reg_103_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln209_fu_225_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                iter_0_lcssa_reg_103 <= ap_const_lv32_0;
            elsif (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6_on_subcall_done))) then 
                iter_0_lcssa_reg_103 <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln213_1_reg_459 <= add_ln213_1_fu_368_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln224_reg_453 <= add_ln224_fu_342_p2;
                select_ln213_1_reg_448 <= select_ln213_1_fu_320_p3;
                select_ln213_reg_442 <= select_ln213_fu_284_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                blocksNeeded_reg_429 <= blocksNeeded_fu_219_p2;
                icmp_ln209_reg_433 <= icmp_ln209_fu_225_p2;
                select_ln207_reg_423 <= select_ln207_fu_207_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_p_cond_out_ap_vld = ap_const_logic_1))) then
                p_cond_loc_fu_64 <= grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_p_cond_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_sizeNeeded_3_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                sizeNeeded_3_loc_fu_72 <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_sizeNeeded_3_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sub_ln203_out_ap_vld = ap_const_logic_1))) then
                sub_ln203_loc_fu_60 <= grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sub_ln203_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln209_fu_225_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                trunc_ln209_reg_437 <= trunc_ln209_fu_231_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_done, grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_done, grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_done, grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_done, ap_block_state6_on_subcall_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state10, ap_CS_fsm_state12)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (ap_const_boolean_0 = ap_block_state6_on_subcall_done))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state10) and (grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    add_ln213_1_fu_368_p2 <= std_logic_vector(unsigned(add_ln213_fu_362_p2) + unsigned(select_ln213_1_reg_448));
    add_ln213_fu_362_p2 <= std_logic_vector(unsigned(zext_ln213_1_fu_358_p1) + unsigned(zext_ln213_fu_348_p1));
    add_ln224_fu_342_p2 <= std_logic_vector(unsigned(tmp_24_cast_fu_334_p3) + unsigned(trunc_ln224_fu_328_p1));
    add_ln226_fu_377_p2 <= std_logic_vector(unsigned(add_ln224_reg_453) + unsigned(ap_const_lv17_200));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_done)
    begin
        if ((grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_done)
    begin
        if ((grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_done)
    begin
        if ((grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_done)
    begin
        if ((grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(ap_block_state6_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state6_on_subcall_done)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state6_on_subcall_done_assign_proc : process(icmp_ln209_reg_433, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_done)
    begin
                ap_block_state6_on_subcall_done <= ((icmp_ln209_reg_433 = ap_const_lv1_1) and (grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_iter_0_lcssa_phi_fu_107_p4_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out, iter_0_lcssa_reg_103)
    begin
        if (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_phi_mux_iter_0_lcssa_phi_fu_107_p4 <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out;
        else 
            ap_phi_mux_iter_0_lcssa_phi_fu_107_p4 <= iter_0_lcssa_reg_103;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= blocksNeeded_reg_429;
    blocksNeeded_fu_219_p2 <= std_logic_vector(signed(sext_ln207_fu_215_p1) + signed(ap_const_lv25_1));
    grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_ap_start_reg;
    grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start <= grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_ap_start_reg;
    grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_ap_start_reg;
    grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start <= grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_ap_start_reg;
    grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start <= grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_ap_start_reg;
    icmp_ln209_fu_225_p2 <= "1" when (signed(grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out) > signed(ap_const_lv32_0)) else "0";

    message5binary_address0_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_address0, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_address0, ap_CS_fsm_state2)
    begin
        if (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            message5binary_address0 <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            message5binary_address0 <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_address0;
        else 
            message5binary_address0 <= "XXXXXXXXXXXX";
        end if; 
    end process;


    message5binary_ce0_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_ce0, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_ce0, ap_CS_fsm_state2)
    begin
        if (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            message5binary_ce0 <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_message5binary_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            message5binary_ce0 <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_message5binary_ce0;
        else 
            message5binary_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    messageBlocks_address0_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_address0, grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_address0, grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_address0, ap_CS_fsm_state10, ap_CS_fsm_state12, zext_ln213_2_fu_373_p1, ap_CS_fsm_state8, zext_ln226_fu_382_p1, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            messageBlocks_address0 <= zext_ln226_fu_382_p1(17 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            messageBlocks_address0 <= zext_ln213_2_fu_373_p1(17 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            messageBlocks_address0 <= grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            messageBlocks_address0 <= grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_address0;
        elsif (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            messageBlocks_address0 <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_address0;
        else 
            messageBlocks_address0 <= "XXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    messageBlocks_ce0_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_ce0, grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_ce0, grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_ce0, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            messageBlocks_ce0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            messageBlocks_ce0 <= grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            messageBlocks_ce0 <= grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_ce0;
        elsif (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            messageBlocks_ce0 <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_ce0;
        else 
            messageBlocks_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    messageBlocks_d0_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_d0, grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_d0, grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_d0, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            messageBlocks_d0 <= ap_const_lv5_0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            messageBlocks_d0 <= ap_const_lv5_11;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            messageBlocks_d0 <= grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            messageBlocks_d0 <= grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_d0;
        elsif (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            messageBlocks_d0 <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_d0;
        else 
            messageBlocks_d0 <= "XXXXX";
        end if; 
    end process;


    messageBlocks_we0_assign_proc : process(icmp_ln209_reg_433, ap_CS_fsm_state6, grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_we0, grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_we0, grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_we0, ap_CS_fsm_state10, ap_CS_fsm_state12, ap_CS_fsm_state8, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            messageBlocks_we0 <= ap_const_logic_1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            messageBlocks_we0 <= grp_padv4_Pipeline_VITIS_LOOP_223_4_fu_148_messageBlocks_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            messageBlocks_we0 <= grp_padv4_Pipeline_VITIS_LOOP_215_3_fu_140_messageBlocks_we0;
        elsif (((icmp_ln209_reg_433 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            messageBlocks_we0 <= grp_padv4_Pipeline_VITIS_LOOP_209_2_fu_131_messageBlocks_we0;
        else 
            messageBlocks_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_and_f_cast_fu_292_p3 <= (ap_const_lv8_0 & trunc_ln213_fu_236_p1);
    p_and_t3_cast_fu_306_p3 <= (ap_const_lv8_0 & sub_ln213_2_fu_300_p2);
    select_ln207_fu_207_p3 <= 
        sub_ln207_fu_187_p2 when (p_cond_loc_fu_64(0) = '1') else 
        zext_ln207_1_fu_203_p1;
    select_ln213_1_fu_320_p3 <= 
        sub_ln213_3_fu_314_p2 when (tmp_fu_244_p3(0) = '1') else 
        p_and_f_cast_fu_292_p3;
    select_ln213_fu_284_p3 <= 
        sub_ln213_1_fu_268_p2 when (tmp_fu_244_p3(0) = '1') else 
        trunc_ln213_3_fu_274_p4;
        sext_ln207_fu_215_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln207_fu_207_p3),25));

    sub_ln207_fu_187_p2 <= std_logic_vector(unsigned(ap_const_lv24_0) - unsigned(zext_ln207_fu_183_p1));
    sub_ln213_1_fu_268_p2 <= std_logic_vector(unsigned(ap_const_lv7_0) - unsigned(trunc_ln213_2_fu_258_p4));
    sub_ln213_2_fu_300_p2 <= std_logic_vector(unsigned(ap_const_lv9_0) - unsigned(trunc_ln213_fu_236_p1));
    sub_ln213_3_fu_314_p2 <= std_logic_vector(unsigned(ap_const_lv17_0) - unsigned(p_and_t3_cast_fu_306_p3));
    sub_ln213_fu_252_p2 <= std_logic_vector(unsigned(ap_const_lv16_0) - unsigned(trunc_ln213_1_fu_240_p1));
    tmp_24_cast_fu_334_p3 <= (trunc_ln224_1_fu_331_p1 & ap_const_lv9_0);
    tmp_fu_244_p3 <= ap_phi_mux_iter_0_lcssa_phi_fu_107_p4(31 downto 31);
    tmp_s_fu_351_p3 <= (select_ln213_reg_442 & ap_const_lv9_0);
    trunc_ln207_1_fu_173_p4 <= sub_ln203_loc_fu_60(31 downto 9);
    trunc_ln207_2_fu_193_p4 <= grp_padv4_Pipeline_VITIS_LOOP_203_1_fu_123_sizeNeeded_out(31 downto 9);
    trunc_ln209_fu_231_p1 <= grp_padv4_Pipeline_VITIS_LOOP_10_1_fu_115_strLength_out(31 - 1 downto 0);
    trunc_ln213_1_fu_240_p1 <= ap_phi_mux_iter_0_lcssa_phi_fu_107_p4(16 - 1 downto 0);
    trunc_ln213_2_fu_258_p4 <= sub_ln213_fu_252_p2(15 downto 9);
    trunc_ln213_3_fu_274_p4 <= ap_phi_mux_iter_0_lcssa_phi_fu_107_p4(15 downto 9);
    trunc_ln213_fu_236_p1 <= ap_phi_mux_iter_0_lcssa_phi_fu_107_p4(9 - 1 downto 0);
    trunc_ln224_1_fu_331_p1 <= select_ln207_reg_423(8 - 1 downto 0);
    trunc_ln224_fu_328_p1 <= select_ln207_reg_423(17 - 1 downto 0);
    zext_ln207_1_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln207_2_fu_193_p4),24));
    zext_ln207_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln207_1_fu_173_p4),24));
    zext_ln213_1_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_351_p3),17));
    zext_ln213_2_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln213_1_reg_459),64));
    zext_ln213_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln213_reg_442),17));
    zext_ln226_fu_382_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln226_fu_377_p2),64));
end behav;
